apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: demo-ingress
spec:
 backend:
 	serviceName: demo-service
 	servicePort: 80
	
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: fanout-ingress
spec:
 rules:
 - http:
 	paths:
 	- path: /hello
 	  backend:
 	 	serviceName: hello
 	   	servicePort: 80
 	- path: /goodbye
      backend:
 	 	serviceName: goodbye
 	   	servicePort: 80
		
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
	name: demo-ingress
spec:
 	tls:
 	- secretName: demo-tls-secret
 	  backend:
 	 	serviceName: demo-service
 	   	servicePort: 80