apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
 name: add-cache
spec:
 selector:
 	matchLabels:
 		role: frontend
 volumeMounts:
 	- mountPath: /cache
 	  name: cache-volume
 volumes:
	- name: cache-volume
	  emptyDir: {}